import { NextResponse } from "next/server";
import { withAdmin } from "@/lib/api-middleware";
import { logger } from "@/lib/logger";

/**
 * GET /api/admin/content-factory
 *
 * Returns:
 *  - stats: prompt count, blog post count, pending drafts count, created this week
 *  - pending: blog post drafts and prompt drafts generated by content-factory
 *  - history: last 20 content_generation_log entries
 */
export const GET = withAdmin(async (_req, supabase) => {
  try {
    const oneWeekAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString();

    const [
      promptCountResult,
      blogCountResult,
      pendingBlogsResult,
      pendingPromptsResult,
      createdThisWeekResult,
      historyResult,
      categoriesResult,
    ] = await Promise.all([
      // Total active prompts in library
      supabase
        .from("public_library_prompts")
        .select("*", { count: "exact", head: true })
        .eq("is_active", true),

      // Total published blog posts
      supabase
        .from("blog_posts")
        .select("*", { count: "exact", head: true })
        .eq("status", "published"),

      // Pending blog drafts (all drafts — filter content-factory in JS)
      supabase
        .from("blog_posts")
        .select("id, title, slug, excerpt, category, content, meta_title, meta_description, tags, read_time, created_at, source_metadata")
        .eq("status", "draft")
        .order("created_at", { ascending: false }),

      // Pending prompt drafts (all inactive — filter content-factory in JS)
      supabase
        .from("public_library_prompts")
        .select("id, title, prompt, use_case, variables, output_format, quality_checks, category_id, capability_mode, created_at, source_metadata")
        .eq("is_active", false)
        .order("created_at", { ascending: false }),

      // Content-factory items created this week (generation log is the source of truth)
      supabase
        .from("content_generation_log")
        .select("*", { count: "exact", head: true })
        .eq("status", "completed")
        .gte("created_at", oneWeekAgo),

      // Last 20 generation log entries
      supabase
        .from("content_generation_log")
        .select("*")
        .order("created_at", { ascending: false })
        .limit(20),

      // Library categories (for dropdowns)
      supabase
        .from("library_categories")
        .select("id, name_he")
        .order("sort_order"),
    ]);

    if (promptCountResult.error) {
      logger.error("[admin/content-factory] GET prompt count error:", promptCountResult.error);
    }
    if (blogCountResult.error) {
      logger.error("[admin/content-factory] GET blog count error:", blogCountResult.error);
    }
    if (pendingBlogsResult.error) {
      logger.error("[admin/content-factory] GET pending blogs error:", pendingBlogsResult.error);
    }
    if (pendingPromptsResult.error) {
      logger.error("[admin/content-factory] GET pending prompts error:", pendingPromptsResult.error);
    }
    if (historyResult.error) {
      logger.error("[admin/content-factory] GET history error:", historyResult.error);
    }

    // Filter content-factory items in JS (JSONB filter unreliable in Supabase JS)
    const pendingBlogs = (pendingBlogsResult.data ?? []).filter(
      (b: { source_metadata?: { generated_by?: string } }) => b.source_metadata?.generated_by === "content-factory"
    );
    const pendingPrompts = (pendingPromptsResult.data ?? []).filter(
      (p: { source_metadata?: { generated_by?: string } }) => p.source_metadata?.generated_by === "content-factory"
    );

    const stats = {
      totalPrompts: promptCountResult.count ?? 0,
      totalBlogPosts: blogCountResult.count ?? 0,
      pendingCount: pendingBlogs.length + pendingPrompts.length,
      createdThisWeek: createdThisWeekResult.count ?? 0,
    };

    return NextResponse.json({
      stats,
      pendingBlogs,
      pendingPrompts,
      history: historyResult.data ?? [],
      categories: categoriesResult.data ?? [],
    });
  } catch (err) {
    logger.error("[admin/content-factory] GET error:", err);
    return NextResponse.json({ error: "Internal error" }, { status: 500 });
  }
});
