import { NextResponse } from "next/server";
import { validateAdminSession } from "@/lib/admin/admin-security";
import { logger } from "@/lib/logger";

/**
 * GET /api/admin/content-factory
 *
 * Returns:
 *  - stats: prompt count, blog post count, pending drafts count, created this week
 *  - pending: blog post drafts and prompt drafts generated by content-factory
 *  - history: last 20 content_generation_log entries
 */
export async function GET() {
  try {
    const { error, supabase } = await validateAdminSession();
    if (error || !supabase) {
      return NextResponse.json({ error: error || "Forbidden" }, { status: 403 });
    }

    const oneWeekAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString();

    const [
      promptCountResult,
      blogCountResult,
      pendingBlogsResult,
      pendingPromptsResult,
      createdThisWeekResult,
      historyResult,
    ] = await Promise.all([
      // Total active prompts in library
      supabase
        .from("public_library_prompts")
        .select("*", { count: "exact", head: true })
        .eq("is_active", true),

      // Total published blog posts
      supabase
        .from("blog_posts")
        .select("*", { count: "exact", head: true })
        .eq("status", "published"),

      // Pending blog drafts from content-factory
      supabase
        .from("blog_posts")
        .select("id, title, excerpt, category, created_at, source_metadata")
        .eq("status", "draft")
        .filter("source_metadata->>generated_by", "eq", "content-factory")
        .order("created_at", { ascending: false }),

      // Pending prompt drafts from content-factory
      supabase
        .from("public_library_prompts")
        .select("id, title, use_case, category_id, created_at, source_metadata")
        .eq("is_active", false)
        .filter("source_metadata->>generated_by", "eq", "content-factory")
        .order("created_at", { ascending: false }),

      // Content-factory items created this week
      supabase
        .from("blog_posts")
        .select("*", { count: "exact", head: true })
        .eq("status", "draft")
        .filter("source_metadata->>generated_by", "eq", "content-factory")
        .gte("created_at", oneWeekAgo),

      // Last 20 generation log entries
      supabase
        .from("content_generation_log")
        .select("*")
        .order("created_at", { ascending: false })
        .limit(20),
    ]);

    if (promptCountResult.error) {
      logger.error("[admin/content-factory] GET prompt count error:", promptCountResult.error);
    }
    if (blogCountResult.error) {
      logger.error("[admin/content-factory] GET blog count error:", blogCountResult.error);
    }
    if (pendingBlogsResult.error) {
      logger.error("[admin/content-factory] GET pending blogs error:", pendingBlogsResult.error);
    }
    if (pendingPromptsResult.error) {
      logger.error("[admin/content-factory] GET pending prompts error:", pendingPromptsResult.error);
    }
    if (historyResult.error) {
      logger.error("[admin/content-factory] GET history error:", historyResult.error);
    }

    const stats = {
      totalPrompts: promptCountResult.count ?? 0,
      totalBlogPosts: blogCountResult.count ?? 0,
      pendingCount:
        (pendingBlogsResult.data?.length ?? 0) + (pendingPromptsResult.data?.length ?? 0),
      createdThisWeek: createdThisWeekResult.count ?? 0,
    };

    return NextResponse.json({
      stats,
      pendingBlogs: pendingBlogsResult.data ?? [],
      pendingPrompts: pendingPromptsResult.data ?? [],
      history: historyResult.data ?? [],
    });
  } catch (err) {
    logger.error("[admin/content-factory] GET error:", err);
    return NextResponse.json({ error: "Internal error" }, { status: 500 });
  }
}
