/**
 * Keep `prompt_engines` in step with the engine templates shipped in code.
 *
 * Why this exists: `getEngine()` prefers the DB row over the code default. The
 * rows were seeded once in March 2026 and never touched again, and the lookup
 * (lowercase mode against uppercase rows) never matched them, so production
 * ran the code defaults while the admin editor edited rows nobody read. The
 * lookup is fixed; from now on the row is what users get, and this script is
 * how a template change in code reaches the row. Found 2026-09-02.
 *
 * What it does: instantiates each engine with no config, takes its shipped
 * templates, and writes an idempotent migration that
 *   1. snapshots the current DB templates into `prompt_engine_history`,
 *   2. updates each row to the shipped text, only where it differs.
 * Apply the migration like any other, then commit it.
 *
 * Usage:
 *   npx tsx scripts/sync-prompt-engines.ts            # writes the migration
 *   npx tsx scripts/sync-prompt-engines.ts --stdout   # prints it instead
 *
 * The admin engine editor stays the place for deliberate, hand-made changes;
 * this script exists so a change made in code reaches users, not to overwrite
 * an admin edit blindly. It updates only rows whose text differs from the
 * shipped baseline, and the old text is always kept in the history table.
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { shippedEngineBaselines, type ShippedTemplates as Templates } from "../src/lib/engines/shipped-baselines";

const TAG = "$shipped$";

function quote(text: string): string {
  if (text.includes(TAG)) throw new Error("template contains the dollar-quote tag");
  return `${TAG}${text}${TAG}`;
}

export function buildMigration(baselines: Record<string, Templates>, stamp: string): string {
  const parts: string[] = [];
  parts.push(`-- Generated by scripts/sync-prompt-engines.ts on ${stamp}.
-- Brings prompt_engines up to the templates shipped in code. Idempotent: a
-- row is rewritten only when its text differs, and the previous text is kept
-- in prompt_engine_history first.

CREATE TABLE IF NOT EXISTS public.prompt_engine_history (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  mode text NOT NULL,
  system_prompt_template text NOT NULL,
  user_prompt_template text NOT NULL,
  replaced_at timestamptz NOT NULL DEFAULT now(),
  reason text
);
ALTER TABLE public.prompt_engine_history ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.prompt_engine_history FROM anon, authenticated;
GRANT SELECT ON public.prompt_engine_history TO authenticated;
DROP POLICY IF EXISTS "Admins read engine history" ON public.prompt_engine_history;
CREATE POLICY "Admins read engine history" ON public.prompt_engine_history
  FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.user_roles ur WHERE ur.user_id = (select auth.uid()) AND ur.role = 'admin'));
`);

  for (const [mode, t] of Object.entries(baselines)) {
    const sys = quote(t.system_prompt_template);
    const usr = quote(t.user_prompt_template);
    parts.push(`
-- ${mode}
INSERT INTO public.prompt_engine_history (mode, system_prompt_template, user_prompt_template, reason)
SELECT mode, system_prompt_template, user_prompt_template, 'replaced by shipped baseline ${stamp}'
FROM public.prompt_engines
WHERE mode = '${mode}'
  AND (system_prompt_template IS DISTINCT FROM ${sys} OR user_prompt_template IS DISTINCT FROM ${usr});

UPDATE public.prompt_engines
SET system_prompt_template = ${sys},
    user_prompt_template = ${usr},
    updated_at = now()
WHERE mode = '${mode}'
  AND (system_prompt_template IS DISTINCT FROM ${sys} OR user_prompt_template IS DISTINCT FROM ${usr});
`);
  }
  return parts.join("\n");
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1]);
if (isMain) {
  const now = new Date();
  const stamp = now.toISOString().slice(0, 10);
  const ts = now.toISOString().replace(/[-:T]/g, "").slice(0, 12) + "00";
  const sql = buildMigration(shippedEngineBaselines(), stamp);
  if (process.argv.includes("--stdout")) {
    process.stdout.write(sql);
  } else {
    const file = path.resolve(
      path.dirname(fileURLToPath(import.meta.url)),
      `../supabase/migrations/${ts}_prompt_engines_shipped_baseline.sql`,
    );
    writeFileSync(file, sql);
    console.log(`wrote ${file}`);
  }
}
