// Maps English URL slugs to category IDs and vice versa
export const CATEGORY_SLUG_MAP: Record<string, { id: string; labelHe: string; descriptionHe: string; emoji: string }> = {
  "marketing":      { id: "Marketing",     labelHe: "פרומפטים לשיווק",              descriptionHe: "פרומפטים מקצועיים לשיווק דיגיטלי, קמפיינים, מיתוג ופרסום",     emoji: "📢" },
  "sales":          { id: "Sales",          labelHe: "פרומפטים למכירות",             descriptionHe: "פרומפטים לשיפור תהליכי מכירה, הצעות מחיר ומשא ומתן",            emoji: "💰" },
  "customer-support": { id: "CustomerSupport", labelHe: "פרומפטים לתמיכת לקוחות",  descriptionHe: "פרומפטים למענה לקוחות, פתרון בעיות ושיפור שירות",               emoji: "🎧" },
  "product":        { id: "Product",        labelHe: "פרומפטים לניהול מוצר",         descriptionHe: "פרומפטים לניהול מוצר, תכנון פיצ'רים וחווית משתמש",              emoji: "📦" },
  "operations":     { id: "Operations",     labelHe: "פרומפטים לתפעול",              descriptionHe: "פרומפטים לייעול תהליכים, ניהול פרויקטים ולוגיסטיקה",            emoji: "⚙️" },
  "hr":             { id: "HR",             labelHe: "פרומפטים למשאבי אנוש",         descriptionHe: "פרומפטים לגיוס, הדרכה, תרבות ארגונית וניהול עובדים",            emoji: "👥" },
  "dev":            { id: "Dev",            labelHe: "פרומפטים לפיתוח תוכנה",        descriptionHe: "פרומפטים לכתיבת קוד, דיבוג, ארכיטקטורה ו-DevOps",              emoji: "💻" },
  "education":      { id: "Education",      labelHe: "פרומפטים לחינוך",              descriptionHe: "פרומפטים למורים, סטודנטים, מבחנים ותוכניות לימוד",             emoji: "📚" },
  "legal":          { id: "Legal",          labelHe: "פרומפטים למשפטים",             descriptionHe: "פרומפטים לניסוח חוזים, ייעוץ משפטי ורגולציה",                  emoji: "⚖️" },
  "creative":       { id: "Creative",       labelHe: "פרומפטים ליצירתיות",           descriptionHe: "פרומפטים לכתיבה יצירתית, סיפורים, שירה ותסריטים",             emoji: "🎨" },
  "social":         { id: "Social",         labelHe: "פרומפטים לרשתות חברתיות",      descriptionHe: "פרומפטים לפוסטים, סטוריז, רילס ותוכן וויראלי",                 emoji: "📱" },
  "seo":            { id: "SEO",            labelHe: "פרומפטים ל-SEO",               descriptionHe: "פרומפטים לקידום אורגני, מילות מפתח ותוכן ממוקד SEO",           emoji: "🔍" },
  "finance":        { id: "Finance",        labelHe: "פרומפטים לפיננסים",            descriptionHe: "פרומפטים לניתוח פיננסי, תקציבים והשקעות",                      emoji: "📊" },
  "healthcare":     { id: "Healthcare",     labelHe: "פרומפטים לבריאות",             descriptionHe: "פרומפטים לבריאות, רפואה ואורח חיים בריא",                      emoji: "🏥" },
  "ecommerce":      { id: "Ecommerce",      labelHe: "פרומפטים לאי-קומרס",           descriptionHe: "פרומפטים לחנויות אונליין, תיאורי מוצרים והמרות",               emoji: "🛒" },
  "real-estate":    { id: "RealEstate",     labelHe: "פרומפטים לנדל\"ן",             descriptionHe: "פרומפטים למכירת נכסים, שיווק דירות והשכרה",                    emoji: "🏠" },
  "strategy":       { id: "Strategy",       labelHe: "פרומפטים לאסטרטגיה",           descriptionHe: "פרומפטים לתכנון אסטרטגי, ניתוח שוק ומודלים עסקיים",           emoji: "🎯" },
  "design":         { id: "Design",         labelHe: "פרומפטים לעיצוב",              descriptionHe: "פרומפטים לעיצוב גרפי, UI/UX ומיתוג ויזואלי",                   emoji: "🖌️" },
  "data":           { id: "Data",           labelHe: "פרומפטים לדאטה",               descriptionHe: "פרומפטים לניתוח נתונים, SQL, ויזואליזציה ו-BI",                emoji: "📈" },
  "automation":     { id: "Automation",     labelHe: "פרומפטים לאוטומציה",           descriptionHe: "פרומפטים לאוטומציה של תהליכים, סקריפטים ואינטגרציות",         emoji: "🤖" },
  "community":      { id: "Community",      labelHe: "פרומפטים לקהילה",              descriptionHe: "פרומפטים לניהול קהילות, אירועים ומעורבות",                     emoji: "🤝" },
  "nonprofit":      { id: "Nonprofit",      labelHe: "פרומפטים למלכ\"רים",           descriptionHe: "פרומפטים לגיוס תרומות, שיווק חברתי ומגזר שלישי",              emoji: "❤️" },
  "images":         { id: "Images",         labelHe: "פרומפטים ליצירת תמונות",       descriptionHe: "פרומפטים ל-Midjourney, DALL-E ו-Stable Diffusion",             emoji: "🖼️" },
  "general":        { id: "General",        labelHe: "פרומפטים כלליים",              descriptionHe: "פרומפטים כלליים למגוון שימושים יומיומיים",                    emoji: "✨" },
  "cooking":        { id: "Cooking",        labelHe: "פרומפטים לבישול",              descriptionHe: "פרומפטים למתכונים, תכנון ארוחות וטיפים קולינריים",             emoji: "👨‍🍳" },
  "travel":         { id: "Travel",         labelHe: "פרומפטים לטיולים",             descriptionHe: "פרומפטים לתכנון טיולים, מסלולים וחוויות נסיעה",               emoji: "✈️" },
  "sports":         { id: "Sports",         labelHe: "פרומפטים לספורט וכושר",        descriptionHe: "פרומפטים לתוכניות אימון, תזונה ואורח חיים פעיל",              emoji: "🏋️" },
  "personal-dev":   { id: "PersonalDev",    labelHe: "פרומפטים לפיתוח אישי",         descriptionHe: "פרומפטים למוטיבציה, פרודוקטיביות וצמיחה אישית",               emoji: "🌱" },
  "greetings":      { id: "Greetings",      labelHe: "פרומפטים לברכות ואיחולים",     descriptionHe: "פרומפטים לברכות חג, יום הולדת, חתונה ואירועים",               emoji: "🎉" },
  "music":          { id: "Music",          labelHe: "פרומפטים למוזיקה",             descriptionHe: "פרומפטים ליצירת שירים, מילים ולחנים",                         emoji: "🎵" },
};

// Reverse lookup: category ID -> English slug
export const CATEGORY_ID_TO_SLUG: Record<string, string> = Object.fromEntries(
  Object.entries(CATEGORY_SLUG_MAP).map(([slug, { id }]) => [id, slug])
);

// Legacy Hebrew slug -> English slug redirect map (for backwards compatibility)
export const HEBREW_SLUG_TO_ENGLISH: Record<string, string> = {
  "שיווק":          "marketing",
  "מכירות":         "sales",
  "תמיכה":          "customer-support",
  "מוצר":           "product",
  "תפעול":          "operations",
  "משאבי-אנוש":     "hr",
  "פיתוח":          "dev",
  "חינוך":          "education",
  "משפטי":          "legal",
  "קריאייטיב":      "creative",
  "סושיאל":         "social",
  "קידום-אתרים":    "seo",
  "פיננסים":        "finance",
  "בריאות":         "healthcare",
  "אי-קומרס":       "ecommerce",
  "נדלן":           "real-estate",
  "אסטרטגיה":       "strategy",
  "עיצוב":          "design",
  "דאטה":           "data",
  "אוטומציה":       "automation",
  "קהילה":          "community",
  "מלכר":           "nonprofit",
  "תמונות":         "images",
  "כללי":           "general",
  "בישול":          "cooking",
  "טיולים":         "travel",
  "ספורט-וכושר":    "sports",
  "פיתוח-אישי":     "personal-dev",
  "ברכות":          "greetings",
  "מוזיקה":         "music",
};
