export const CATEGORY_OPTIONS = [
  { id: "None", label: "ללא" },
  { id: "General", label: "כללי" },
  { id: "Marketing", label: "שיווק" },
  { id: "Sales", label: "מכירות" },
  { id: "CustomerSupport", label: "תמיכה" },
  { id: "Product", label: "מוצר" },
  { id: "Operations", label: "תפעול" },
  { id: "HR", label: "משאבי אנוש" },
  { id: "Dev", label: "פיתוח" },
  { id: "Education", label: "חינוך" },
  { id: "Legal", label: "משפטי" },
  { id: "Creative", label: "קריאייטיב" },
  { id: "Social", label: "סושיאל" },
  { id: "Finance", label: "פיננסים" },
  { id: "Healthcare", label: "בריאות" },
  { id: "Ecommerce", label: "אי־קומרס" },
  { id: "RealEstate", label: "נדל\"ן" },
  { id: "Strategy", label: "אסטרטגיה" },
  { id: "Design", label: "עיצוב" },
  { id: "Data", label: "דאטה" },
  { id: "Automation", label: "אוטומציה" },
  { id: "Community", label: "קהילה" },
  { id: "Nonprofit", label: "מלכ\"ר" },
];

export const CATEGORY_LABELS: Record<string, string> = {
  None: "ללא",
  Marketing: "שיווק",
  Sales: "מכירות",
  CustomerSupport: "תמיכה",
  Product: "מוצר",
  Operations: "תפעול",
  HR: "משאבי אנוש",
  Dev: "פיתוח",
  Education: "חינוך",
  Legal: "משפטי",
  Creative: "קריאייטיב",
  Social: "סושיאל",
  General: "כללי",
  Finance: "פיננסים",
  Healthcare: "בריאות",
  Ecommerce: "אי־קומרס",
  RealEstate: "נדל\"ן",
  Strategy: "אסטרטגיה",
  Design: "עיצוב",
  Data: "דאטה",
  Automation: "אוטומציה",
  Community: "קהילה",
  Nonprofit: "מלכ\"ר",
};

export const PERSONAL_DEFAULT_CATEGORY = "כללי";

export const QUICK_ACTIONS = [
  { label: "קצר יותר", instruction: "קצר יותר. שמור על המבנה והדגשים המרכזיים." },
  { label: "יותר אסרטיבי", instruction: "יותר אסרטיבי, ישיר וממוקד תוצאה." },
  { label: "יותר פרקטי", instruction: "יותר פרקטי, עם צעדים מדידים ודוגמאות קצרות." },
];
